#!/bin/bash
bbpass=""
bblogin=""
for p in $(pass $USER/git/bitbucket); do
    if [ ! -n "$bbpass" ]; then
        bbpass=$p
    elif [ "$p" == "login:" ] || [ "$p" == "user:" ]; then
        continue
    elif [ ! -n "$bblogin" ]; then
        bblogin=$p
    else
        break
    fi
done
key=`cat $HOME/.ssh/id_rsa.pub`
curl --user $bblogin:$bbpass -X POST https://bitbucket.org/api/1.0/users/$bblogin/ssh-keys --data-urlencode "key=$key" --data-urlencode "label=guld-key"
