#!/bin/bash
bbpass=""
bblogin=""
for p in $(pass $USER/git/bitbucket); do
    if [ ! -n "$bbpass" ]; then
        bbpass=$p
    elif [ "$p" == "login:" ] || [ "$p" == "user:" ]; then
        continue
    elif [ ! -n "$bblogin" ]; then
        bblogin=$p
    else
        break
    fi
done
flag="-c"
user=$2
if [ "$3" == "public" ]; then
    flag="-o"
elif [ "$2" == "public" ]; then
    flag="-o"
    user=$USER
elif [ ! -n "$2" ]; then
    user=$USER
fi
echo $bblogin $bbpass
if [ ! -n "$1" ] || [ ! -n "$user" ]; then
    echo "usage:"
    echo "    bb-create-repo name username <public>"
    echo "        Creates repo with name under account username."
    echo "        Default is to create private repo unless public specified last"
else
    bb create -w $user $flag -u $bblogin -p $bbpass $1
fi

