#!/bin/bash
GULDNAME=$(guld-name)
GULDHOME="/home/$GULDNAME"
flag="-o"
user=$2
if [ "$1" == "--private" ]; then
    flag="-c"
    shift
fi
if [ "$3" == "--private" ]; then
    flag="-c"
elif [ "$2" == "--private" ]; then
    flag="-c"
    user=$GULDNAME
elif [ ! -n "$2" ]; then
    user=$GULDNAME
fi
bblogin=$(git config --file /home/$GULDNAME/.gitconfig host.bitbucket)
bbowner=$(git config --file /home/$user/.gitconfig host.bitbucket)
if [ ! -n "$bbowner" ]; then
    bbowner=$user
fi
bbpass=$(pass $GULDNAME/git/bitbucket | head -n 1 2> /dev/null)
ghlogin=$(git config --file /home/$GULDNAME/.gitconfig host.github)
ghowner=$(git config --file /home/$user/.gitconfig host.github)
if [ ! -n "$ghowner" ]; then
    ghowner=$user
fi
ghpass=$(pass $GULDNAME/git/github | head -n 1 2> /dev/null)
gllogin=$(git config --file /home/$GULDNAME/.gitconfig host.gitlab)
glowner=$(git config --file /home/$user/.gitconfig host.gitlab)
if [ ! -n "$v" ]; then
    glowner=$user
fi
gltoken=$(pass $GULDNAME/git/gitlab-token | head -n 1 2> /dev/null)
glpass=$(pass $GULDNAME/git/gitlab | head -n 1 2> /dev/null)
glns=$(curl -s --header "Private-Token: $gltoken" "https://gitlab.com/api/v4/namespaces?search=$glowner" | python -c "import sys, json; print json.load(sys.stdin)[0]['id']" 2>/dev/null)
if [ ! -n "$1" ] || [ ! -n "$user" ]; then
    echo "usage:"
    echo "    create-repo name username <--private>"
    echo "        Creates repo with name under account username."
    echo "        Default is to create public repo unless --private specified"
elif [ "$user" != "$USER" ] && [ "$ghowner" != "$ghlogin" ]; then
    if [ -n "$ghlogin" ] && [ -n "$ghpass" ]; then
        w=$(curl -s -u $ghlogin:$ghpass https://api.github.com/orgs/$ghowner/repos -d "{ \"name\": \"$1\" }")
    fi
    if [ -n "$bblogin" ] && [ -n "$bbpass" ]; then
        w=$(bb create -w $bbowner $flag -u $bblogin -p $bbpass $1)
    fi
    if [ -n "$gllogin" ] && [ -n "$glpass" ] && [ -n "$glns" ]; then
        w=$(curl -s --header "Private-Token: $gltoken" -X POST "https://gitlab.com/api/v4/projects" --data-urlencode "name=$1" --data-urlencode "default_branch=$GULDNAME" --data-urlencode "namespace_id=$glns")
    fi
else
    if [ -n "$ghlogin" ] && [ -n "$ghpass" ]; then
        w=$(curl -s -u $ghlogin:$ghpass https://api.github.com/user/repos -d "{ \"name\": \"$1\" }")
    fi
    if [ -n "$bblogin" ] && [ -n "$bbpass" ]; then
        w=$(bb create -w $bbowner $flag -u $bblogin -p $bbpass $1)
    fi
    if [ -n "$gllogin" ] && [ -n "$glpass" ] && [ -n "$glns" ]; then
        w=$(curl -s --header "Private-Token: $gltoken" -X POST "https://gitlab.com/api/v4/projects" --data-urlencode "name=$1" --data-urlencode "default_branch=$glowner" --data-urlencode "namespace_id=$glns")
    fi
fi
