#!/bin/bash
GULDNAME=$(guld-name)
GULDHOME="/home/$GULDNAME"
p=$(pwd)
last=$p
while [ $p != $GULDHOME ]; do
    last=$p
    git add -A
    git commit -m "update"
    git-push-user $GULDNAME
    cd ..
    p=$(pwd)
done
guld-update-perspective $last $GULDNAME
