#!/bin/bash
p=$(pwd)
home=/home/$USER
if [ "$p" == "/home" ]; then
    ghp=blocktree
elif [ "$p" == "$home" ]; then
    ghp=$USER
else
    n=${#home}
    p=${p:$n}
    ghp=${p//\//-}
fi
username=$(git config --file /home/$USER/.gitconfig user.username)
glname=$(git config --file /home/$USER/.gitconfig host.gitlab)
if [ -n "$glname" ]; then
    $(git remote add $username-gl git@gitlab.org:$glname/$ghp.git)
    $(git remote set-url $username-gl git@gitlab.org:$glname/$ghp.git)
    $(git remote add $username git@gitlab.org:$glname/$ghp.git)
    $(git remote set-url $username git@gitlab.org:$glname/$ghp.git)
fi
ghname=$(git config --file /home/$USER/.gitconfig host.github)
if [ -n "$ghname" ]; then
    $(git remote add $username-gh git@github.com:$ghname/$ghp.git)
    $(git remote set-url $username-gh git@github.com:$ghname/$ghp.git)
    $(git remote add $username git@github.com:$ghname/$ghp.git)
    $(git remote set-url $username git@github.com:$ghname/$ghp.git)
fi
bbname=$(git config --file /home/$USER/.gitconfig host.bitbucket)
if [ -n "$bbname" ]; then
    $(git remote add $username-bb git@bitbucket.org:$bbname/$ghp.git)
    $(git remote set-url $username-bb git@bitbucket.org:$bbname/$ghp.git)
    $(git remote add $username git@bitbucket.org:$bbname/$ghp.git)
    $(git remote set-url $username git@bitbucket.org:$bbname/$ghp.git)
fi

