#!/bin/bash
#branches=$(git for-each-ref --format='%(refname)' refs/heads/ | grep -o [^/]*$)
if [ -n "$1" ]; then
    GULDNAME=$1
else
    GULDNAME=$(guld-name)
fi
git fetch $GULDNAME
git merge $GULDNAME/$GULDNAME

