#!/bin/bash
preqs="curl gpg2 gpa git pass qtpass ledger pip npm"

# detect OS
if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    if [ "$NAME" != "Ubuntu" ]; then
        echo "Only Ubuntu install currently automated. Assuming you have pre-reqs: $preqs"
    else
        for req in $preqs; do
            w=$(which $req)
            if [ "$req" == "gpg2" ]; then
                req="gnupg2"
            fi
            if [ "$req" == "pip" ]; then
                req="python-pip"
            fi
            if [ ! -n "$w" ]; then
                if [ "$req" == "npm" ]; then
                    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
                    # TODO sense newer than 10 when it comes?
                    nvm i 10
                else
                    sudo apt-get install -y "$req"
                fi
            fi
        done
    fi
fi

npm i -g rimraf guld-cli guld-env guld-git-path guld-git-host-gitlab guld-git-host guld-git-host-bitbucket guld-fs-cli guld-env-cli guld-pass-cli guld-fs-str-replace-cli guld-git-host-cli guld-git-path-cli guld-git-cli guld-git-remote-cli guld-user-cli guld-keys-cli guld-mail-cli guld-ledger guld-git-dir guld-git-remote guld-cli-run

mkdir -p $HOME/dotfiles $HOME/ledger/GULD $HOME/keys/pgp $HOME/keys/ssh
cd $HOME
git init

guld-user init
uname=$(guld-user name)
mkdir -p $HOME/dotfiles/$uname $HOME/ledger/GULD/$uname $HOME/keys/pgp $HOME/keys/ssh
mkdir -p $HOME/.password-store/$uname/git/
guld-mail init
guld-keys init
ukey=$(guld keys list | grep -o ^[A-Z0-9]*)
guld-pass init $ukey
guld-git-host init

init () {
    if [ ! -d "$1" ]; then
        mkdir -p $1
        cd $1
        git init
    fi
    guld-git-host repo-create
    if [ "$1" = "$HOME" ]; then
        git remote add guld https://bitbucket.org/guld/perspective.git
        git checkout -b guld || git checkout guld
    fi
    guld-git-remote delete
    guld-git-remote add
    git pull guld guld
    $(git checkout -b $uname || git checkout $uname 2&> /dev/null)
    git push $uname $uname
}

init $HOME
init "$HOME/Documents"
init "$HOME/dotfiles"
init "$HOME/.password-store"
init "$HOME/Pictures"
init "$HOME/devices"
init "$HOME/io"
init "$HOME/keys"
#cd "$HOME/keys"
#git submodule update --init pgp
#git submodule update --init ssh
init "$HOME/keys/pgp"
mkdir -p "$HOME/keys/pgp/$uname"
guld-keys export -a >> "$HOME/keys/pgp/$uname/$ukey.asc"
init "$HOME/keys/ssh"
init "$HOME/ledger"
init "$HOME/ledger/GULD"
init "$HOME/tech"
init "$HOME/.blocktree"
