#!/bin/bash
if [ -n "$1" ]; then
    GULDNAME=$1
else
    GULDNAME=$(guld-name)
fi
p=$(pwd)
if [ "$p" == "/home" ]; then
    echo .blocktree
    exit 0
fi
pp=${p/\/home\//}
if [[ $pp != *"/"* ]]; then
    echo perspective
    exit 0
fi
OIFS=$IFS
IFS='/'
for d in $pp
do
    user=$d
    break
done
IFS=$OIFS
pi=${p/\/home\/$USER\//}
if [ "$p" != "$pi" ]; then
    echo ${pi//\//-}
    exit 0
fi
pi=${p/\/home\/$GULDNAME\//}
if [ "$p" != "$pi" ]; then
    echo ${pi//\//-}
    exit 0
fi
pi=${p/\/home\/$user\//}
if [ "$p" != "$pi" ]; then
    echo ${pi//\//-}
    exit 0
fi
exit 1
