#!/bin/bash
GULDNAME=$(guld-name)
branches=$(git for-each-ref --format='%(refname)' refs/heads/ | grep -o [^/]*$)
guld-push-user $GULDNAME
for branch in $branches; do
    git checkout $branch
    git merge $GULDNAME
    guld-push-user $branch
done
git checkout $GULDNAME
