#!/bin/bash
if [ -n "$1" ]; then
    GULDNAME=$1
else
    GULDNAME=$(guld-name)
fi
p=$(pwd)
if [ "$p" == "/home" ]; then
    echo .blocktree
    exit 0
elif [ "$p" == "$GULDHOME" ]; then
    echo $GULDNAME
    exit 0
else
    pi=${p/\/home\/$USER/}
    if [ "$p" != "$pi" ]; then
        echo ${pi//\//-}
        exit 0
    fi
    pi=${p/\/home\/$GULDHOME/}
    if [ "$p" != "$pi" ]; then
        echo ${pi//\//-}
        exit 0
    fi
fi
echo ${p:6}

