#!/bin/bash
GULDNAME=$(guld-name)
if [ -n "$1" ]; then
    GULDNAME=$1
fi
GULDHOME="/home/$GULDNAME"

cd $HOME/.blocktree
git fetch $GULDNAME
git merge $GULDNAME/$GULDNAME
cd ..
git add .blocktree
last=${last/$GULDHOME\//}
git add "$last"
status=$(git status -s)
if [ -n "$status" ]; then
    git commit -m "update"
    git-push-user $GULDNAME
    cd ..
    git add $GULDNAME
    git commit -m "update"
    git-push-user $GULDNAME
fi
