#!/bin/bash
GULDNAME=$(guld-name)
branches=$(git for-each-ref --format='%(refname)' refs/heads/ | grep -o [^/]*$)
guld-push-user $GULDNAME
for branch in $branches; do
    if [ "$branch" != "$GULDNAME" ]; then
        git checkout $branch
        git merge $GULDNAME
        guld-push-user $branch
    fi
done
git checkout $GULDNAME
